import type { ModelInfo, ProviderName } from './types'

export const MODEL_REGISTRY: ModelInfo[] = [
  // ── OpenRouter (via OpenRouter gateway) ────────────────────────────────────
  {
    id: 'meta-llama/llama-3.3-70b-instruct:free',
    name: 'Llama 3.3 70B (Free)',
    provider: 'openrouter',
    contextWindow: 131072,
    inputCostPer1k: 0,
    outputCostPer1k: 0,
    supportsTools: true,
    supportsVision: false,
    isFree: true,
    description: 'Powerful free model. Great for most tasks at zero cost.',
    recommended: true,
  },
  {
    id: 'google/gemini-flash-1.5',
    name: 'Gemini Flash 1.5',
    provider: 'openrouter',
    contextWindow: 1000000,
    inputCostPer1k: 0.000075,
    outputCostPer1k: 0.0003,
    supportsTools: true,
    supportsVision: true,
    isFree: false,
    description: '1M token context. Excellent for large codebases and long docs.',
  },
  {
    id: 'google/gemini-2.0-flash-exp:free',
    name: 'Gemini 2.0 Flash (Free)',
    provider: 'openrouter',
    contextWindow: 1000000,
    inputCostPer1k: 0,
    outputCostPer1k: 0,
    supportsTools: true,
    supportsVision: true,
    isFree: true,
    description: 'Free experimental Gemini 2.0 with 1M context and vision.',
  },
  {
    id: 'anthropic/claude-sonnet-4-6',
    name: 'Claude Sonnet 4.6',
    provider: 'openrouter',
    contextWindow: 200000,
    inputCostPer1k: 0.003,
    outputCostPer1k: 0.015,
    supportsTools: true,
    supportsVision: true,
    isFree: false,
  },
  {
    id: 'anthropic/claude-opus-4-6',
    name: 'Claude Opus 4.6',
    provider: 'openrouter',
    contextWindow: 200000,
    inputCostPer1k: 0.015,
    outputCostPer1k: 0.075,
    supportsTools: true,
    supportsVision: true,
    isFree: false,
    description: 'Most capable Claude model. Best for complex reasoning and planning.',
  },
  {
    id: 'openai/gpt-4o',
    name: 'GPT-4o',
    provider: 'openrouter',
    contextWindow: 128000,
    inputCostPer1k: 0.0025,
    outputCostPer1k: 0.01,
    supportsTools: true,
    supportsVision: true,
    isFree: false,
  },
  {
    id: 'openai/gpt-4o-mini',
    name: 'GPT-4o Mini',
    provider: 'openrouter',
    contextWindow: 128000,
    inputCostPer1k: 0.00015,
    outputCostPer1k: 0.0006,
    supportsTools: true,
    supportsVision: true,
    isFree: false,
    description: 'Fast and cheap OpenAI model. Great for quick structured tasks.',
  },
  {
    id: 'deepseek/deepseek-r1',
    name: 'DeepSeek R1',
    provider: 'openrouter',
    contextWindow: 64000,
    inputCostPer1k: 0.0005,
    outputCostPer1k: 0.0015,
    supportsTools: false,
    supportsVision: false,
    isFree: false,
    description: 'Strong reasoning model. Great for math, code analysis, and logic.',
  },

  // ── Anthropic (direct) ─────────────────────────────────────────────────────
  {
    id: 'claude-sonnet-4-6',
    name: 'Claude Sonnet 4.6',
    provider: 'anthropic',
    contextWindow: 200000,
    inputCostPer1k: 0.003,
    outputCostPer1k: 0.015,
    supportsTools: true,
    supportsVision: true,
    isFree: false,
    recommended: true,
  },
  {
    id: 'claude-opus-4-6',
    name: 'Claude Opus 4.6',
    provider: 'anthropic',
    contextWindow: 200000,
    inputCostPer1k: 0.015,
    outputCostPer1k: 0.075,
    supportsTools: true,
    supportsVision: true,
    isFree: false,
    description: 'Most capable Claude model. Best for Lyra and complex orchestration.',
  },
  {
    id: 'claude-haiku-4-5-20251001',
    name: 'Claude Haiku 4.5',
    provider: 'anthropic',
    contextWindow: 200000,
    inputCostPer1k: 0.0008,
    outputCostPer1k: 0.004,
    supportsTools: true,
    supportsVision: true,
    isFree: false,
    description: 'Fast and cheap. Great for memory extraction and background tasks.',
  },

  // ── Groq (free tier) ───────────────────────────────────────────────────────
  {
    id: 'llama-3.3-70b-versatile',
    name: 'Llama 3.3 70B',
    provider: 'groq',
    contextWindow: 128000,
    inputCostPer1k: 0,
    outputCostPer1k: 0,
    supportsTools: true,
    supportsVision: false,
    isFree: true,
    description: '500+ tokens/sec. Free tier (14,400 req/day). Fastest inference available.',
    recommended: true,
  },
  {
    id: 'llama-3.1-8b-instant',
    name: 'Llama 3.1 8B Instant',
    provider: 'groq',
    contextWindow: 128000,
    inputCostPer1k: 0,
    outputCostPer1k: 0,
    supportsTools: true,
    supportsVision: false,
    isFree: true,
    description: 'Extremely fast 8B model. Best for Courier and background memory tasks.',
  },
  {
    id: 'deepseek-r1-distill-llama-70b',
    name: 'DeepSeek R1 Distill 70B',
    provider: 'groq',
    contextWindow: 128000,
    inputCostPer1k: 0,
    outputCostPer1k: 0,
    supportsTools: false,
    supportsVision: false,
    isFree: true,
    description: 'Free reasoning model on Groq. Strong for code and logic tasks.',
  },

  // ── OpenAI (direct) ────────────────────────────────────────────────────────
  {
    id: 'gpt-4o',
    name: 'GPT-4o',
    provider: 'openai',
    contextWindow: 128000,
    inputCostPer1k: 0.0025,
    outputCostPer1k: 0.01,
    supportsTools: true,
    supportsVision: true,
    isFree: false,
  },
  {
    id: 'gpt-4o-mini',
    name: 'GPT-4o Mini',
    provider: 'openai',
    contextWindow: 128000,
    inputCostPer1k: 0.00015,
    outputCostPer1k: 0.0006,
    supportsTools: true,
    supportsVision: true,
    isFree: false,
  },
  {
    id: 'o3-mini',
    name: 'o3-mini',
    provider: 'openai',
    contextWindow: 200000,
    inputCostPer1k: 0.0011,
    outputCostPer1k: 0.0044,
    supportsTools: true,
    supportsVision: false,
    isFree: false,
    description: 'OpenAI reasoning model. Great for multi-step planning tasks.',
  },

  // ── Ollama (local) ─────────────────────────────────────────────────────────
  {
    id: 'llama3.2:3b',
    name: 'Llama 3.2 3B (Local)',
    provider: 'ollama',
    contextWindow: 128000,
    inputCostPer1k: 0,
    outputCostPer1k: 0,
    supportsTools: false,
    supportsVision: false,
    isFree: true,
    description: 'Fast, lightweight local model. ~2GB. Good for quick tasks.',
    recommended: true,
  },
  {
    id: 'llama3.3:latest',
    name: 'Llama 3.3 70B (Local)',
    provider: 'ollama',
    contextWindow: 128000,
    inputCostPer1k: 0,
    outputCostPer1k: 0,
    supportsTools: false,
    supportsVision: false,
    isFree: true,
    description: 'Powerful local model. ~40GB download. Requires 32GB+ RAM.',
  },
  {
    id: 'deepseek-coder:6.7b',
    name: 'DeepSeek Coder 6.7B (Local)',
    provider: 'ollama',
    contextWindow: 16000,
    inputCostPer1k: 0,
    outputCostPer1k: 0,
    supportsTools: false,
    supportsVision: false,
    isFree: true,
    description: 'Code-focused local model. ~4GB. Great for Forge.',
  },
  {
    id: 'mistral:latest',
    name: 'Mistral 7B (Local)',
    provider: 'ollama',
    contextWindow: 32000,
    inputCostPer1k: 0,
    outputCostPer1k: 0,
    supportsTools: false,
    supportsVision: false,
    isFree: true,
    description: 'Efficient general-purpose local model. ~4GB.',
  },
  {
    id: 'phi4:latest',
    name: 'Phi-4 (Local)',
    provider: 'ollama',
    contextWindow: 16000,
    inputCostPer1k: 0,
    outputCostPer1k: 0,
    supportsTools: false,
    supportsVision: false,
    isFree: true,
    description: 'Microsoft Phi-4 small language model. ~8GB. Surprisingly capable.',
  },
]

export const PROVIDER_META: Record<ProviderName, {
  label: string
  icon: string
  color: string
  description: string
  keyPrefix: string
  keyPlaceholder: string
  docsNote: string
}> = {
  openrouter: {
    label: 'OpenRouter',
    icon: 'fa-solid fa-route',
    color: '#818cf8',
    description: 'One key unlocks 100+ models — free Llama, Claude, GPT-4o, Gemini, and more. Recommended starting point.',
    keyPrefix: 'sk-or-',
    keyPlaceholder: 'sk-or-v1-…',
    docsNote: 'Get your free key at openrouter.ai/keys — create an account and generate a key. Free tier includes Llama 3.3 70B and Gemini Flash at zero cost.',
  },
  anthropic: {
    label: 'Anthropic',
    icon: 'fa-solid fa-a',
    color: '#f97316',
    description: 'Direct access to Claude Sonnet, Opus, and Haiku. Best if you have an existing Anthropic subscription.',
    keyPrefix: 'sk-ant-',
    keyPlaceholder: 'sk-ant-api03-…',
    docsNote: 'Get your key at console.anthropic.com/settings/keys. Requires a paid Anthropic account.',
  },
  openai: {
    label: 'OpenAI',
    icon: 'fa-solid fa-o',
    color: '#34d399',
    description: 'Direct access to GPT-4o, o3-mini, and other OpenAI models.',
    keyPrefix: 'sk-',
    keyPlaceholder: 'sk-proj-…',
    docsNote: 'Get your key at platform.openai.com/api-keys. Requires an OpenAI account with billing.',
  },
  groq: {
    label: 'Groq',
    icon: 'fa-solid fa-bolt',
    color: '#fbbf24',
    description: 'Free tier Llama 3.3 70B at 500+ tokens/sec. The fastest inference available — great for Courier.',
    keyPrefix: 'gsk_',
    keyPlaceholder: 'gsk_…',
    docsNote: 'Get your free key at console.groq.com/keys. No credit card required for the free tier.',
  },
  ollama: {
    label: 'Ollama',
    icon: 'fa-solid fa-server',
    color: '#22d3ee',
    description: 'Run AI completely locally. No keys, no costs, no data leaving your machine.',
    keyPrefix: '',
    keyPlaceholder: 'No key required',
    docsNote: 'Ollama runs on your machine at localhost:11434. Install it once and run any supported model offline.',
  },
}

export function getModelsForProvider(provider: ProviderName): ModelInfo[] {
  return MODEL_REGISTRY.filter((m) => m.provider === provider)
}

export function getModelById(id: string, provider?: ProviderName): ModelInfo | undefined {
  return MODEL_REGISTRY.find((m) => m.id === id && (!provider || m.provider === provider))
}

export function getCostForModel(modelId: string): { input: number; output: number } {
  const model = MODEL_REGISTRY.find((m) => m.id === modelId)
  return { input: model?.inputCostPer1k ?? 0.003, output: model?.outputCostPer1k ?? 0.015 }
}
